controller_names:
  - arm_trajectory_controller
  - omni_base_controller
  - head_trajectory_controller
  - gripper_controller

arm_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - arm_lift_joint
    - arm_flex_joint
    - arm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint
    - wrist_ft_sensor_frame_joint

omni_base_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - odom_x
    - odom_y
    - odom_t

head_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - head_pan_joint
    - head_tilt_joint

gripper_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - hand_motor_joint
